node{
  label 'windows_node'
 stage('SCM Checkout'){ 
   git 'https://github.com/sachinj1806/UbuntuJob' 
    }
 stage('Compile-Package'){
  //get maven home path
  //def mvnHome = tool name: 'maven', type: 'maven'
 // sh '${mvnHome}/bin/mvn test' 
 //bat '${mvnHome}/bin/mvn test' 
  //bat label: '', script: tool name: 'maven', type: 'maven'/bin/mvn test'
  bat 'mvn test'
 }
}
